modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]

modId="blockstar"

version="1.0-alpha"

displayName="Blockstar"

logoFile= "../blockstar.png"

authors="Ninni"

description='''
An animal mod that tries to add new animals with niches and personality to the Minecraft world
'''

[[dependencies.blockstar]]
modId="forge"
mandatory=true
versionRange="[47.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.blockstar]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
