modLoader="javafml"
loaderVersion="[46,)"
license="GNU LESSER GENERAL PUBLIC LICENSE"
issueTrackerURL="https://github.com/N1nn1/minestrel/issues"
[[mods]]
modId="minestrel"
version="0.0.1"
displayName="Minestrel"
displayURL=""
authors="Ninni, VoidArkana"
credits=""
description=""
#logoFile="assets/minestrel/textures/misc/mod_logo.png"
[[dependencies.minestrel]]
modId="forge"
mandatory=true
versionRange="[47.1.3,)"
ordering="NONE"
side="BOTH"