modLoader="javafml"
loaderVersion="[46,)"
license="GNU LESSER GENERAL PUBLIC LICENSE"
issueTrackerURL="https://github.com/N1nn1/blockstar/issues"
[[mods]]
modId="blockstar"
version="0.0.1"
displayName="Blockstar"
displayURL=""
authors="Ninni"
credits=""
description=""
#logoFile="assets/minestrel/textures/misc/mod_logo.png"
[[dependencies.blockstar]]
modId="forge"
mandatory=true
versionRange="[47.1.3,)"
ordering="NONE"
side="BOTH"